# Generated by Django 5.2.12 on 2026-04-06 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='post_photo')),
                ('content', models.TextField(max_length=500)),
                ('item_name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('max_participants', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=100)),
                ('participants', models.ManyToManyField(blank=True, related_name='joined_posts', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
