# Generated by Django 5.2.12 on 2026-03-19 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(max_length=500)),
                ('item_name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('max_participants', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=100)),
            ],
        ),
    ]
