# Generated by Django 5.2.12 on 2026-03-30 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_purchase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='joined_posts', to='group_purchase.user'),
        ),
    ]
